# Generated by Django 3.2.4 on 2021-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rates_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
