# Generated by Django 3.2.4 on 2021-06-22 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_rates_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Min rate is 1'), django.core.validators.MaxValueValidator(5, message='Max rate is 5')])),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_ids', to='cars.car')),
            ],
        ),
    ]
